version: '3'
services:
  mongo:
    image: mongo:3.2
    ports:
      - 28017:27017
  redis:
    image: redis:3.2.5
    environment:
        - REDIS_PASSWORD=redis
    ports:
      - 6479:6379
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - 3406:3306