openapi: 3.0.0
info:
  version: 0.0.1
  title: Simple App
paths:
  /hello:
    get:
      description: Returns 'Hello' to the caller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  "/hey/{name}":
    get:
      description: Returns 'Hey' to the caller
      operationId: hey
      parameters:
        - name: name
          in: path
          description: The name of the person to whom to say hello
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
servers:
  - url: "http://localhost:3000/"
components:
  schemas:
    MessageResponse:
      required:
        - message
      properties:
        message:
          type: string
